terraform/main.tf

ref: https://github.com/pypa/warehouse/issues/4793

add include:amazonses.com to the pypi.org SPF record

---

terraform/warehouse/vcl/main.vcl

Fixes https://github.com/pypa/warehouse/issues/2546

Configure Varnish to not send Age header

---

terraform/file-hosting/vcl/main.vcl

See:
* https://github.com/pypa/warehouse/issues/4687
* https://github.com/pypa/conveyor/issues/5

Allow /packages to be loaded cross-origin

---

terraform/warehouse/vcl/main.vcl

re: https://github.com/pypa/warehouse/issues/6834

disregard Accept-Language header for now

---

terraform/docs-hosting/vcl/main.vcl
terraform/file-hosting/vcl/main.vcl
terraform/warehouse/vcl/main.vcl

This addresses https://github.com/pypa/warehouse/issues/7008.

Limit Strict-Transport-Security header to HTTPS only

---

terraform/dns/main.tf
terraform/docs-hosting/main.tf
terraform/email/main.tf
terraform/file-hosting/main.tf
terraform/gmail/main.tf
terraform/warehouse/main.tf

moves our major endpoints to 1day and all records for like mail and verification and stuff to 1 hour.

bump ttls for DNS

---

terraform/file-hosting/vcl/main.vcl
terraform/warehouse/vcl/main.vcl

described in https://github.com/pypa/pypi-support/issues/978

implement rolling blackouts of non-SNI support

---

terraform/file-hosting/main.tf
terraform/warehouse/main.tf

see https://github.com/pypa/linehaul-cloud-function/issues/14#issuecomment-853312983

reduce the interval that we feed the GCF based linehaul

---

terraform/file-hosting/vcl/main.vcl
terraform/file-hosting/vcl/staging.vcl

Fixes https://github.com/pypa/conveyor/issues/11

Include CORS headers on cross-origin range requests

---

terraform/file-hosting/vcl/main.vcl
terraform/file-hosting/vcl/staging.vcl

Ref https://github.com/pypa/conveyor/issues/11

Handle CORS preflight request

---

terraform/warehouse/vcl/main.vcl

This reverts commit 46408f5f934673587a6a295c8723dd00be30ecca.

Revert "Add trailing slashes to all request URLs (#74)"

---

terraform/warehouse/vcl/main.vcl

pairs with https://github.com/pypa/warehouse/pull/11546 to serve all possible URLs for JSON API from canonicalized project name as a step towards eventually redirecting non-canonincalized URLs to the canonical ones.

Serve JSON API from canonical endpoints

---

terraform/email/main.tf
terraform/main.tf

we're not sure where old postmark reports are going

update dmarc reporting

---

terraform/warehouse/vcl/main.vcl

ref: https://github.com/pypi/warehouse/pull/12173

match behavior of backend for xmlrpc search disable

---

terraform/file-hosting/fastly-service.tf
terraform/file-hosting/vcl/files.vcl

enable segmented caching for file hosting service

---

terraform/file-hosting/vcl/files.vcl

These headers are needed in vcl_log to feed linehaul. Unfortunately we can't _unset_ them in vcl_log so this proposes renaming them to at least make clear they're specific to PyPI.

fix linehaul logging

---

terraform/file-hosting/fastly-service.tf
terraform/file-hosting/main.tf
terraform/file-hosting/versions.tf

Makes no functional changes to our file hosting service, just creates:
- B2 Buckets & Application Keys for Fastly, configures in a snippet for future work
- S3 Glacier Instant Retrieval Buckets & Access Keys for Fastly, configures in a snippet for future work

Phase 0: Object storage migration resources

---

terraform/file-hosting/fastly-service.tf
terraform/file-hosting/main.tf
terraform/file-hosting/vcl/files.vcl

Phase 0.0: Object storage migration

---

terraform/file-hosting/vcl/files.vcl

most of our fallbacks at this point are due to this.

handle plus signs in URLs when dispatching to B2

---

terraform/file-hosting/fastly-service.tf
terraform/file-hosting/vcl/files.vcl

Log failed fallback attempts to fastly
Don't health check S3 Glacier, reqs aren't free and we at least have good logging now?
Fix configuration.

B2 s3g failover, final

---

terraform/dns/main.tf
terraform/main.tf

add helpscout spf/dkim

---

terraform/warehouse/vcl/main.vcl

ref: https://developer.fastly.com/reference/http/http-headers/Fastly-Client-IP/

Distrust Fastly-Client-IP from... clients

---

terraform/image-proxy/main.tf

Fighting quotes

---

terraform/image-proxy/main.tf

fight the quotes

---

terraform/image-proxy/main.tf

set override_host

---

terraform/main.tf

create camo cdn service for production

Create module for pypi-camo

---

terraform/email/main.tf
terraform/versions.tf

https://github.com/hashicorp/terraform-provider-aws/blob/7f7c17ac86fc77c1c7adf26384c9a76a7994deae/internal/service/sns/topic.go#L158-L163

Upgrade SNS topics to SignatureVersion 2

---

terraform/warehouse/vcl/main.vcl

Refs: https://github.com/pypi/inspector/pull/158

feat: allow query param through on malware report

---

terraform/main.tf
terraform/warehouse/main.tf
terraform/warehouse/ngwaf.tf

Use fastly key instead of not use fastly key

fix: use fastly key

---

terraform/main.tf

Update DMARC reporting for pypi.org

---

terraform/warehouse/main.tf

use one condition instead of not one

chore: use single condition

---

terraform/warehouse/vcl/main.vcl

Refs: https://github.com/pypi/warehouse/pull/17326

feat: add Korean language

---

terraform/main.tf

bug: disable ngwaf

---

terraform/main.tf

enable ngwaf

---

terraform/warehouse/ngwaf.tf

Seeing if there is maybe a weird ordering that is causing the ngwaf waffling

Flip manage state to false for NGWAF snippets

---

terraform/main.tf

Revert "Disable NGWAF", aka "Enable NGWAF"

---

terraform/main.tf

Reverts pypi/infra#196
[youtube.com/watch?v=3KTilOsXBmU](https://www.youtube.com/watch?v=3KTilOsXBmU)

Revert "Revert "Disable NGWAF", aka "Disable NGWAF""

---

terraform/main.tf

Reverts pypi/infra#198
[youtube.com/watch?v=3KTilOsXBmU](https://www.youtube.com/watch?v=3KTilOsXBmU)

Revert "Revert "Revert "Disable NGWAF", aka "Enable NGWAF"""

---

terraform/warehouse/vcl/main.vcl

Enabling Fastly NGWAF led to spats of 503s in our metrics after enabling NGWAF. After troubleshooting with support we were told:
> the 503 occurs because our compute platform closes the connection when it receives the request with the non-ASCII characters, which Varnish treats as a backend error, returning a 503 to the client.
and provided this as a work around.

send HTTP 400 explicitly when non-ASCII characters are used in url

---

terraform/email/main.tf

After running with 25% for a while, increase to 75% for some time before we go to 100%.

chore: increase quarantine percentage

---

terraform/email/main.tf

We've been at 75% for a month with no issues. Go to 100.
I think next step is to move from quarantine to reject?

dmarc policy, quarantine 75 -> 100

---

terraform/inspector/main.tf
terraform/main.tf

- disable ngwaf
- fix health route path

chore: disable ngwaf, fix health route

---

terraform/inspector/ngwaf.tf

Adds a 30s delay dependency which itself depends on a service to be alive... in hopes that it resolves sporadic issues like in https://app.terraform.io/app/psf/workspaces/pypi-infra/runs/run-BV9Ns9xcQ7UK93ie?organization_name=psf
i have the most minimal amount of faith that this will help/work/fix anything

fix: try adding delay to ngwaf svc link
