terraform/email/main.tf
terraform/main.tf

This is blocked on merging https://github.com/pypa/warehouse/pull/3580.

Switch from using a SQS Queue to SNS Web Hooks

---

terraform/docs-hosting/main.tf
terraform/docs-hosting/vcl/main.vcl
terraform/main.tf

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
~ update in-place
+ module.docs-hosting.aws_route53_record.docs
id:                                      <computed>
allow_overwrite:                         "true"
fqdn:                                    <computed>
name:                                    "pythonhosted.org"
records.#:                               "4"
records.1145861945:                      "151.101.129.63"
records.1545709132:                      "151.101.193.63"
records.2084396284:                      "151.101.1.63"
records.2212431859:                      "151.101.65.63"
ttl:                                     "60"
type: …
```

Deploy a fastly service to front the legacy pythonhosted.org docs

---

terraform/docs-hosting/main.tf
terraform/file-hosting/main.tf
terraform/main.tf

Instead of duplicating (with slightly different!) logic for locating the fastly endpoint, reuse the same logic everywhere with a central mapping of domains to fastly endpoints to fastly A, AAAA, and CNAME records.

Use the same endpoint logic in all modules

---

terraform/file-hosting/main.tf
terraform/main.tf
terraform/warehouse/main.tf

* Turns on health checks for the S3 bucket.
* Enables static fallback for URLs matching ``^/packages/[a-f0-9]{2}/[a-f0-9]{2}/[a-f0-9]{60}/`` if their backend (S3) is unhealthy.
* Enables static fallback for URLs matching ``^/pypi/[^/]+(/[^/]+)?/json`` if their backend (Warehouse) is unhealthy.
Between this and the other PR, they both expect that ``mirror.dub1.pypi.io`` will function with a host header of ``pypi.io`` or ``files.pythonhosted.org``.

Static fallback

---

terraform/docs-hosting/vcl/main.vcl
terraform/file-hosting/vcl/main.vcl
terraform/warehouse/main.tf
terraform/warehouse/vcl/main.vcl

This moves the pretty 503 logic to later in the request/response cycle. Previously we were checking if the backend was healthy or not in ``vcl_recv`` which bypasses the cache completely so even if we had non-stale cached pages for a request it wouldn't serve them. This also defeated the ``stale-if-error`` directive, which would serve stale content if the backend was down and we had it laying around.
This logic waits until the very end, until we're in ``vcl_error`` without any stale content to serve, and then it returns a pretty, synthetic 503 error page. In order to do this I had to turn our VCL into a template so terraform could inject the pretty 503 html as a synthetic response, since Fastly doesn't make it possible to add a response object to the ``vcl_error`` block.
This is taken from …

Move Pretty 503 to later in the request/response cycle

---

terraform/file-hosting/main.tf
terraform/warehouse/main.tf

This resolves some outstanding 5xx errors at edge.
1) Gives backends a bit more time to connect. `/pypi` XMLRPC requests coming from the legacy service were seeing some trouble with regularity.
2) Ups error_threshold for backends. Since we don't have Multiple backends for warehouse anymore and just a single endpoint, it's probably a bad idea to go into an error state if a single error occurs.
3) Improves S3 Error Logging to include Fastly's request status and a service time (to debug timeouts)

tune connect_timeout and error_threshold for backends

---

terraform/dns/main.tf
terraform/main.tf

```
~ module.dns.aws_route53_record.google-verify
records.#:          "1" => "2"
records.1535138413: "google-site-verification=YdrllWIiutXFzqhEamHP4HgCoh88dTFzb2A6QFljooc" => "google-site-verification=YdrllWIiutXFzqhEamHP4HgCoh88dTFzb2A6QFljooc"
records.831471624:  "" => "google-site-verification=ZI8zeHE6SWuJljW3f4csGetjOWo4krvjf13tdORsH4Y"
Plan: 0 to add, 1 to change, 0 to destroy.
```

support multiple google-site-verification TXT records

---

terraform/email/main.tf
terraform/main.tf

```
+ module.testpypi-email.aws_route53_record.primary_amazonses_dkim_record[0]
id:                              <computed>
allow_overwrite:                 "true"
fqdn:                            <computed>
name:                            "${element(aws_ses_domain_dkim.primary.dkim_tokens, count.index)}._domainkey.${var.domain}"
records.#:                       <computed>
ttl:                             "1800"
type:                            "CNAME"
zone_id:                         "Z2BIT24T5LM0F3"
+ module.testpypi-email.aws_route53_record.primary_amazonses_dkim_record[1]
id:                              <computed>
allow_overwrite:                 "true"
fqdn:                            <computed>
name: …
```

setup SES/SNS for testpypi email

---

terraform/main.tf
terraform/warehouse/main.tf
terraform/warehouse/worker.tf

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
+ module.pypi.aws_iam_policy.pypi_worker
id:                                <computed>
arn:                               <computed>
description:                       "R/W Access to PyPI's SQS Worker Queue"
name:                              "PyPIWorkerSQS"
path:                              "/"
policy:                            "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"sqs:ListQueues\"\n      ],\n     \"Resource\": \"*\"\n    },\n    {\n      \"Effect\": \"Allow\",\n      \"Action\": [\n          \"sqs:DeleteMessage\",\n …
```

Setup a SQS Queue for PyPI

---

terraform/warehouse/main.tf

This regressed when setting up the new service.
```
~ module.pypi.fastly_service_v1.pypi
condition.#:                                  "2" => "3"
condition.1122403973.name:                    "Primary Failure (Mirror-able)" => "Primary Failure (Mirror-able)"
condition.1122403973.priority:                "1" => "1"
condition.1122403973.statement:               "(!req.backend.healthy || req.restarts > 0) && (req.url ~ \"^/simple/\" || req.url ~ \"^/pypi/[^/]+(/[^/]+)?/json$\")" => "(!req.backend.healthy || req.restarts > 0) && (req.url ~ \"^/simple/\" || req.url ~ \"^/pypi/[^/]+(/[^/]+)?/json$\")"
condition.1122403973.type:                    "REQUEST" => "REQUEST"
condition.1505353239.name:                    "5xx Error" => "5xx Error"
condition.1505353239.priority:                "10" => …
```

restore prohibition against bandersnatch versions <1.4

---

terraform/main.tf

```
+ module.testpypi-email.aws_route53_record.primary_amazonses_dmarc_record
id:                 <computed>
allow_overwrite:    "true"
fqdn:               <computed>
name:               "_dmarc.test.pypi.org"
records.#:          "1"
records.3458306614: "v=DMARC1; p=none; rua=mailto:re+qjfavuizyth@dmarc.postmarkapp.com; fo=1; adkim=r; aspf=r"
ttl:                "60"
type:               "TXT"
zone_id:            "Z2BIT24T5LM0F3"
Plan: 1 to add, 0 to change, 0 to destroy.
```

add dmarc for test.pypi.org

---

terraform/email/main.tf
terraform/main.tf

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
~ update in-place
~ module.dns.aws_route53_record.apex_txt
records.1535138413: "google-site-verification=YdrllWIiutXFzqhEamHP4HgCoh88dTFzb2A6QFljooc" => "google-site-verification=YdrllWIiutXFzqhEamHP4HgCoh88dTFzb2A6QFljooc"
records.689124498:  "v=spf1 include:_spf.google.com include:amazonses.com -all" => ""
records.760501546:  "" => "v=spf1 include:_spf.google.com -all"
records.831471624:  "google-site-verification=ZI8zeHE6SWuJljW3f4csGetjOWo4krvjf13tdORsH4Y" => "google-site-verification=ZI8zeHE6SWuJljW3f4csGetjOWo4krvjf13tdORsH4Y"
+ module.email.aws_route53_record.primary_amazonses_spf_record
id: …
```

Move Amazon SES SPF headers to the correct domain

---

terraform/warehouse/vcl/main.vcl

Ref https://github.com/pypa/warehouse/issues/2921
This was originally done via the Fastly UI and undone by #42.

Add manage route to whitelist

---

terraform/warehouse/vcl/main.vcl

Pairs nicely with https://github.com/pypa/warehouse/pull/6802.
Prevents query parameters from being stripped from `/locale/` and adds a synthetic `PyPI-Locale` header which we can vary on.
References:
* https://www.fastly.com/blog/best-practices-using-vary-header
* https://support.fastly.com/hc/en-us/community/posts/360040444812-Pull-cookie-values-without-regular-expressions

Handle locales

---

terraform/warehouse/vcl/main.vcl

Without a default the first language to load a page became the default if no locale is set

default PyPI-Locale header to english

---

terraform/warehouse/vcl/main.vcl

This should hide the existence of PyPI-Locale in the Vary header from end users, without impacting shields.

Hide Vary: PyPI-Locale from downstream, Vary on Cookie

---

terraform/dns/main.tf
terraform/docs-hosting/main.tf
terraform/email/main.tf
terraform/file-hosting/main.tf
terraform/warehouse/main.tf

We had just over a billion DNS queries in December which is ~$400 in credit usage for AWS.
This should reduce our DNS spend by a pretty penny, but could probably be pushed out to an hour or so for many of the higher volume endpoints.

bump DNS ttls

---

terraform/file-hosting/main.tf
terraform/file-hosting/vcl/main.vcl
terraform/file-hosting/vcl/staging.vcl

This is the first step in migrating to Google Cloud Storage instead of S3. Fastly will first check the GCS bucket for the file before falling back to S3 if it is not found. Next step is to start uploading files to GCS directly and complete a final sync from S3 to GCS, we can then remove the fallback.
Google offers interconnect/peering pricing with Fastly that will reduce our Bandwidth costs for Origin=>Fastly significantly. This should help stabilize our AWS credit usage and allow us to better utilize the Google cloud funding we have available.

files: Use Google Cloud Storage as primary, fallback to S3

---

terraform/file-hosting/main.tf
terraform/file-hosting/vcl/main.vcl
terraform/main.tf
terraform/warehouse/main.tf
terraform/warehouse/vcl/main.vcl

This starts shipping our Linehaul logs to Google Storage instead of S3.
This immediately transitions `pypi.simple_requests` to be fed by the new Cloud Function, no migration or anything interesting is needed here... Fastly will stop shipping logs to the S3 bucket and start sending them to the Google Storage bucket. Since the table is partitioned/clustered we don't have to do any careful handling.
This will _begin_ feeding the new partitioned/clustered `pypi.file_downloads` table. At some day boundary I can clear out this new table for anything older and begin backfilling from the `pypi.downloadsYYYYMMDD` tables.
Eventually we can stop feeding the current syslog linehaul consumer, deprecate the old sharded tables etc.

Start migration to GCP based linehaul

---

terraform/warehouse/main.tf

BOM has been having trouble with 'unhealthy backends'
AFAICT this is not the pypi backends themselves slowing down or failing health checks :/

ease up our health check for pypi backends

---

terraform/warehouse/vcl/main.vcl

we were still paying the cost of parsing all that XML at the backend for every request before denying it, this sheds ~100rps

move xmlrpc search disable out to edge

---

terraform/file-hosting/vcl/main.vcl
terraform/warehouse/vcl/main.vcl

Note: this is already enforced at Fastly's level... but provide a fallback

Forbid clients that do not implement SNI

---

terraform/config.tf
terraform/dns/main.tf
terraform/docs-hosting/main.tf
terraform/docs-hosting/versions.tf
terraform/email/main.tf
terraform/file-hosting/main.tf
terraform/file-hosting/versions.tf
terraform/gmail/main.tf
terraform/lambda-deployer/main.tf
terraform/main.tf
terraform/versions.tf
terraform/warehouse/main.tf
terraform/warehouse/versions.tf
terraform/warehouse/worker.tf

```
Plan: 0 to add, 4 to change, 0 to destroy.
```
Changes:
```
~ resource "fastly_service_vcl" "docs" {
+ activate           = false
~ cloned_version     = 8 -> (known after apply)
id                 = "6RdgH2FOXbKFjczNLQCnxY"
name               = "PyPI Docs Hosting"
}
~ resource "fastly_service_vcl" "files" {
+ activate           = false
~ cloned_version     = 98 -> (known after apply)
+ default_host       = ""
id                 = "62OyyXk6MTgn4a4JO0NbIO"
name               = "PyPI File Hosting"
+ version_comment    = ""
+ logging_s3 {
+ bucket_name        = "psf-fastly-logs-eu-west-1"
+ domain             = "s3-eu-west-1.amazonaws.com"
+ format             = "%%h \"%{now}V\" %%l \"%{req.request}V %{req.url}V\" %{req.proto}V %%>s …
```

upgrade terraform to latest

---

terraform/file-hosting/vcl/staging.vcl

After an outage detailed at https://status.python.org/incidents/bt0tzq7x2fk2 it was recognized that our monitoring for files.pythonhosted.org was flawed. The file being requested was continuously held in cache due to the monitoring itself.
This creates a specifically named url that will never be cached, specifically for monitoring. We want to deploy this so that we can verify it works before pushing to prod.

Monitoring: create a cache bypass for sentinel package in staging

---

terraform/file-hosting/vcl/main.vcl
terraform/file-hosting/vcl/staging.vcl

This will allow us to monitor that files are accessible via Fastly -> GCS regardless of caching status.

prod deploy: Cdn to gcs end to end test file

---

terraform/warehouse/vcl/main.vcl

This removes the need for us to do this on the backend via redirects.

Add trailing slashes to all request URLs

---

terraform/warehouse/vcl/main.vcl

This is an attempt to address https://github.com/pypi/warehouse/issues/12214
It's not clear if there is any technical difference between `req.http.Fastly-FF` and `fastly.ff.visits_this_service`, but the docs now recommend this.

Update VLC guard against caching stale content at edge

---

terraform/main.tf

Fastly will be issuing upcoming renewals with Lets Encrypt, add them as a CAA issuer

add Lets Encrypt to CAA

---

terraform/main.tf

This has been noisy and hasn't provided sufficient insight to determine what is going on with our DKIM alignment

disable DMARC reporting to postmaster@pypi.org

---

terraform/warehouse/main.tf
terraform/warehouse/vcl/main.vcl

Accept language

---

terraform/warehouse/vcl/main.vcl

This ensures only a single value of Accept-Language makes it to our backends, and that it matches PyPI-Locale
Follows on from #109, attempts to resolve https://github.com/pypi/warehouse/issues/12445

normalize Accept-Language header in vcl_recv

---

terraform/file-hosting/fastly-service.tf
terraform/file-hosting/vcl/files.vcl
terraform/warehouse/vcl/main.vcl

We were hitting this when using the Fastly Cache Check API. Bypass VCL SNI check when User-Agent is Fastly/cache-check.
This VCL shouldn't be accessible to people accessing PyPI using Non-SNI clients, as those should be getting the wrong cert at the edge anyway.

allow Fastly/cache-check to bypass SNI disable in VCL

---

terraform/config.tf
terraform/main.tf
terraform/warehouse/main.tf
terraform/warehouse/vcl/main.vcl

Makes some new headers tasty.
- Adds salted hash (browns) to the client IP address. Does not impact existing behaviors, but starts to send the details to the backend
- Adds geo value header based on country name + region and/or city
Needs some extra 👀  and validation - I'm not certain how this gets rolled out to test before prod

Add seasoning

---

terraform/warehouse/vcl/main.vcl

Instead of introducing intermediate renaming prior to sending to the backend, let's preserve the names we received and pass those along

chore: rename headers for consistency

---

terraform/file-hosting/vcl/files.vcl

Fastly can't do compression for us if we have segmented caching enabled.

Do not enable segmented caching for .metadata files

---

terraform/file-hosting/fastly-service.tf

occasionally b2 responses lead to fallbacks to s3 that makes a line jump that catches the eyes of a pypi admin that leads to us looking and finding nothing actionable.
up the timeouts a bit to reduce these redherrings a bit?

ease off on b2 timeouts

---

terraform/warehouse/main.tf
terraform/warehouse/vcl/main.vcl

When performing responses to users, set the Permissions-Policy header to inform the browser that the only functions we actually care about are related to WebAuthN, and nothing else.
Refs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy
Refs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy

chore: add Permissions-Policy header to warehouse

---

terraform/.terraform.lock.hcl
terraform/config.tf
terraform/main.tf
terraform/versions.tf
terraform/warehouse/main.tf
terraform/warehouse/ngwaf.tf
terraform/warehouse/versions.tf

- Adds Fastlys NGWAF to PyPI on both environments, enabling only for test (which is even still in observe only mode)
The "observe" mode is done via SigSci UI at the moment for `pypi-test` site:

feat: add ngwaf to pypi instances

---

terraform/main.tf
terraform/warehouse/main.tf
terraform/warehouse/ngwaf.tf

- Enables PyPI production ngwaf
- Adds var for percentage setting to [manage traffic flow](https://docs.fastly.com/en/ngwaf/edge-waf-deployment-using-the-next-gen-waf-control-panel#traffic-ramping)

feat: enable pypi prod ngwaf

---

terraform/main.tf

re-anables prod ngwaf at 100% as to not arbitrarily pick what traffic is inspected
still in non-blocking mode

chore: enable prod waf

---

terraform/email/main.tf

Set to 25% of a messages to apply the policy, so as to monitor the
behavior of the rollout.

chore: update dmarc to quarantine

---

terraform/warehouse/ngwaf.tf

set `manage_items` to true to have hcl manage the fastly/ngwaf resources
Refs:
- https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_dictionary_items#reapplying-original-items-with-managed_items-if-the-state-of-the-items-drifts
- https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_dynamic_snippet_content#reapplying-original-snippets-with-manage_snippets-if-the-state-of-the-snippets-drifts

fix: explicitly manage ngwaf resources

---

terraform/inspector/main.tf
terraform/inspector/versions.tf
terraform/main.tf

- Puts inspector.pypi.org udner Fastly
- manages also the DNS record on r53
planned changes:
https://app.terraform.io/app/psf/workspaces/pypi-infra/runs/run-fYq8drCE29K3NXHP
currently works under http://inspector-test.pypi.io/

feat: place inspector under fastly

---

terraform/warehouse/vcl/main.vcl

With the current implementation, any requests coming through a Shield node will be annotated with the Shield's geo information instead of the originating client's geo data.
By moving this earlier, to the one place we interact with the `client` object prior to further processing, we ensure that we set the right data at the right time.

fix: move client geolocation earlier to avoid shield
